parameters:
    sms_mailer.class:      Vivait\SMSMailerBundle\Services\SMSMailer

services:
    vivait_sms_mailer:
        class:        "%sms_mailer.class%"
        arguments:    [ @service_container ]
        tags:
            - { name: vivait_settings.register, alias: sms_mailer }

    vivait_sms.esendex:
        class:        Vivait\SMSMailerBundle\Services\EsendexSMSGateway
        arguments:    [ @service_container ]
        tags:
            - { name: vivait_settings.register, alias: sms_esendex }

    vivait_sms.andresandarnold:
        class:        Vivait\SMSMailerBundle\Services\AndrewsAndArnoldSMSGateway
        arguments:    [ @service_container ]
        tags:
            - { name: vivait_settings.register, alias: sms_andrewsandarnold }

    vivait_sms.packetmedia:
        class:        Vivait\SMSMailerBundle\Services\PacketMediaSMSGateway
        arguments:    [ @service_container ]
        tags:
            - { name: vivait_settings.register, alias: sms_packetmedia }